#Please, be patient, the plugin is still in development, and it is possible you will lose
#your config during updates, so backup it before update.
#
#This plugin supports PlaceholderAPI!

settings:
  #Show credits for newcomers or to everyone
  #SET ONLY newcomers OR everyone OR nobody
  show-credits: newcomers

  #Enable titles
  enable-titles: true

  enable-first-time-chat-message: true

  enable-welcome-chat-message: true

plugin-version:
