#Please, be patient, the plugin is still in development, and it is possible you will lose
#your config during updates, so backup it before update.
#
#This plugin supports PlaceholderAPI!

settings:
  #Show credits for newcomers or to everyone
  #SET ONLY newcomers OR everyone OR nobody
  show-credits: newcomers

  #Active titles
  enable-titles: true

  #Main title message
  main-title-message: Welcome!

  #Subtitle message
  subtitle-message: Hey, %player_name% we are glad you came back!
plugin-version:
