# Please, be patient, the plugin is still in development, and it is possible you will lose
# your config during updates, so backup it before update.
#
# This plugin supports PlaceholderAPI!

settings:
  # Enable showing start credits
  enable-credits: true

  # Show credits for newcomers or to everyone
  # SET ONLY newcomers OR everyone
  show-credits: newcomers

  # Check if resource pack was initialized, if not, kick player
  kick-when-no-resource-pack: true

  # Enable titles
  enable-titles: true

  # Enable chat welcome message on player first join
  enable-first-time-chat-message: true

  # Enable welcome message
  enable-welcome-chat-message: true

  # Enable join messages
  enable-join-messages: true

  # Enable join messages
  enable-leave-messages: true

  # Enable custom player join messages - need to set true enable-join-messages!!!!
  enable-custom-join-messages: true

  # Enable custom player join messages - need to set true enable-join-messages!!!!
  enable-custom-leave-messages: true

  # Enable counters
  enable-counters: true

  # Set what database type you want to use - mysql or sqlite
  database-type: sqlite

# If use-database is mysql, setup this!
mysql-settings:

  db-host: localhost

  db-port: 3306

  db-name: databaseName

  db-username: userName

  db-password: dbPasswd
