name: WelcomePlugin
version: '${project.version}'
main: cz.thepatik.welcomeplugin.WelcomePlugin
api-version: '1.20'
depend: [ ProtocolLib ]
softdepend: [ PlaceholderAPI ]
commands:
  welcome:
    description: Welcome plugin command
    permission: welcomeplugin.usage
permissions:
  welcomeplugin.help:
    description: Allows to show help using /welcome help
    default: op
  welcomeplugin.playedtime:
    description: Allows player show played time
    default: op
  welcomeplugin.playerjoins:
    description: Allows showing player joins or other player joins
    default: op
  welcomeplugin.sentmessages:
    description: Allows showing players sent messages
    default: op
  welcomeplugin.showcreditsto:
    description: Allows admins to change option in config to who show credits
    default: op
  welcomeplugin.update:
    description: Allows to check for updates using /welcome update
    default: op
  welcomeplugin.version:
    description: Allows to show plugin version using /welcome version
    default: op
